// <auto-generated />
using System;
using AnotacionElectronica_Leon_VB.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnotacionElectronica_Leon_VB.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819235955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreAsistente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEntrenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Jugador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsCapitan")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId", "NumeroCamiseta")
                        .IsUnique();

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipoGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SetsGanadosLocal")
                        .HasColumnType("int");

                    b.Property<int>("SetsGanadosVisitante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Punto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoAnotadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JugadorAnotadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntosEquipoLocalActual")
                        .HasColumnType("int");

                    b.Property<int>("PuntosEquipoVisitanteActual")
                        .HasColumnType("int");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Puntos");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Rotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion3Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion4Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion5Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion6Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Rotaciones");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipoGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("int");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntosLocal")
                        .HasColumnType("int");

                    b.Property<int>("PuntosVisitante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Jugador", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Punto", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Set", null)
                        .WithMany("Puntos")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Rotacion", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Set", null)
                        .WithMany("Rotaciones")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", null)
                        .WithMany("Sets")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.Navigation("Puntos");

                    b.Navigation("Rotaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
