// <auto-generated />
using System;
using AnotacionElectronica_Leon_VB.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnotacionElectronica_Leon_VB.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.AlineacionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial3Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial4Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial5Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PosicionInicial6Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SustitucionesRealizadas")
                        .HasColumnType("int");

                    b.Property<string>("_jugadorReemplazadoPorLibero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReemplazosLiberoJson");

                    b.Property<string>("_posicionesActuales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PosicionesActualesJson");

                    b.HasKey("Id");

                    b.ToTable("AlineacionesSets", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Arbitro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Federacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroLicencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Arbitros", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Competicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Organizador")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SedePrincipal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Competiciones", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreAsistente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEntrenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipos", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.EventoPartido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OcurrioEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Secuencia")
                        .HasColumnType("int");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.HasIndex("PartidoId", "Secuencia")
                        .IsUnique();

                    b.ToTable("EventosPartido", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.JuegoCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoReglamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Competicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiferenciaMinima")
                        .HasColumnType("int");

                    b.Property<string>("Edicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipoLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Fase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHoraProgramada")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaximoSets")
                        .HasColumnType("int");

                    b.Property<Guid?>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntoCambioCanchaSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetRegular")
                        .HasColumnType("int");

                    b.Property<string>("Recinto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SetsParaGanar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("FechaHoraProgramada");

                    b.HasIndex("PartidoId")
                        .IsUnique()
                        .HasFilter("[PartidoId] IS NOT NULL");

                    b.ToTable("JuegosCalendario", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Jugador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsCapitan")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId", "NumeroCamiseta")
                        .IsUnique();

                    b.ToTable("Jugadores", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoReglamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiferenciaMinima")
                        .HasColumnType("int");

                    b.Property<Guid?>("EquipoGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoLocalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoVisitanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaximoSets")
                        .HasColumnType("int");

                    b.Property<int>("PuntoCambioCanchaSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetRegular")
                        .HasColumnType("int");

                    b.Property<int>("SetsGanadosLocal")
                        .HasColumnType("int");

                    b.Property<int>("SetsGanadosVisitante")
                        .HasColumnType("int");

                    b.Property<int>("SetsParaGanar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoLocalId");

                    b.HasIndex("EquipoVisitanteId");

                    b.ToTable("Partidos", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.PerfilReglamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoReglamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DiferenciaMinima")
                        .HasColumnType("int");

                    b.Property<int>("MaximoSets")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PuntoCambioCanchaSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetDecisivo")
                        .HasColumnType("int");

                    b.Property<int>("PuntosSetRegular")
                        .HasColumnType("int");

                    b.Property<int>("SetsParaGanar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReglamento")
                        .IsUnique();

                    b.ToTable("PerfilesReglamento", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Punto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoAnotadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("HoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("JugadorAnotadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PuntosEquipoLocalActual")
                        .HasColumnType("int");

                    b.Property<int>("PuntosEquipoVisitanteActual")
                        .HasColumnType("int");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Puntos");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Rotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion3Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion4Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion5Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Posicion6Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Rotaciones");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CambioCanchaConfirmado")
                        .HasColumnType("bit");

                    b.Property<int>("DiferenciaMinima")
                        .HasColumnType("int");

                    b.Property<Guid?>("EquipoGanadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsSetDecisivo")
                        .HasColumnType("bit");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroSet")
                        .HasColumnType("int");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PendienteCambioCancha")
                        .HasColumnType("bit");

                    b.Property<bool>("PendienteConfirmacionCierre")
                        .HasColumnType("bit");

                    b.Property<int>("PuntoCambioCancha")
                        .HasColumnType("int");

                    b.Property<int>("PuntosLocal")
                        .HasColumnType("int");

                    b.Property<int>("PuntosParaGanar")
                        .HasColumnType("int");

                    b.Property<int>("PuntosVisitante")
                        .HasColumnType("int");

                    b.Property<Guid?>("UltimoEquipoAlSaqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.SustitucionReglamentaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlineacionSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JugadorEntraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JugadorSaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Posicion")
                        .HasColumnType("int");

                    b.Property<int>("PuntosLocalEnMomento")
                        .HasColumnType("int");

                    b.Property<int>("PuntosVisitanteEnMomento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlineacionSetId");

                    b.ToTable("SustitucionesReglamentarias", (string)null);
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Jugador", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "EquipoLocal")
                        .WithMany()
                        .HasForeignKey("EquipoLocalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", "EquipoVisitante")
                        .WithMany()
                        .HasForeignKey("EquipoVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipoLocal");

                    b.Navigation("EquipoVisitante");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Punto", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Set", null)
                        .WithMany("Puntos")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Rotacion", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Set", null)
                        .WithMany("Rotaciones")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", null)
                        .WithMany("Sets")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.SustitucionReglamentaria", b =>
                {
                    b.HasOne("AnotacionElectronica_Leon_VB.Domain.Entities.AlineacionSet", null)
                        .WithMany("Sustituciones")
                        .HasForeignKey("AlineacionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.AlineacionSet", b =>
                {
                    b.Navigation("Sustituciones");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("AnotacionElectronica_Leon_VB.Domain.Entities.Set", b =>
                {
                    b.Navigation("Puntos");

                    b.Navigation("Rotaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
